spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: users-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: products-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**